#!/usr/bin/env python3
"""
gemma-4-31b-it.py — Interactive installer for nvidia-ollama-bridge

Connects NVIDIA NIM's google/gemma-4-31b-it to Ollama and/or OpenClaw.

Usage:
    python3 gemma-4-31b-it.py            # interactive setup
    python3 gemma-4-31b-it.py --check    # verify existing setup only
"""

import os
import sys
import json
import shutil
import subprocess
import textwrap
import time
from pathlib import Path

# ─── Constants ────────────────────────────────────────────────────────────────

MODEL_ID     = "google/gemma-4-31b-it"
BRIDGE_PORT  = 11545
NIM_BASE_URL = "https://integrate.api.nvidia.com/v1"
SCRIPT_DIR   = Path(__file__).parent.resolve()
BRIDGE_SRC   = SCRIPT_DIR / "nvidia-bridge.mjs"
BRIDGE_OUT   = SCRIPT_DIR / "gemma-4-31b-it.mjs"
ENV_FILE     = Path.home() / ".config" / "nvidia-ollama-bridge" / "env"
OPENCLAW_CFG = Path(os.environ.get(
    "OPENCLAW_CONFIG",
    Path.home() / ".openclaw" / "openclaw.json"
))

# ─── Colours ──────────────────────────────────────────────────────────────────

GREEN  = "\033[0;32m"
YELLOW = "\033[1;33m"
RED    = "\033[0;31m"
BOLD   = "\033[1m"
RESET  = "\033[0m"

def ok(msg):     print(f"{GREEN}✓{RESET} {msg}")
def warn(msg):   print(f"{YELLOW}⚠{RESET} {msg}")
def fail(msg):   print(f"{RED}✗{RESET} {msg}")
def info(msg):   print(f"  {msg}")
def header(msg): print(f"\n{BOLD}{msg}{RESET}")

# ─── Helpers ──────────────────────────────────────────────────────────────────

def ask(prompt, default=None):
    suffix = f" [{default}]" if default is not None else ""
    try:
        val = input(f"{prompt}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return val if val else default

def which(cmd):
    return shutil.which(cmd) is not None

def run(cmd, **kwargs):
    return subprocess.run(cmd, shell=isinstance(cmd, str), **kwargs)

# ─── Prerequisites ────────────────────────────────────────────────────────────

def check_prereqs():
    header("Checking prerequisites")
    missing = []
    for bin_, label in [("node", "Node.js >= 18"), ("python3", "Python 3")]:
        if which(bin_):
            ok(f"{label} found")
        else:
            fail(f"{label} not found"); missing.append(label)
    if missing:
        info("Install missing tools and retry.")
        return False
    return True

# ─── Step 1: API key ──────────────────────────────────────────────────────────

def get_api_key():
    header("Step 1 — NVIDIA API Key")
    key = os.environ.get("NVIDIA_API_KEY", "").strip()
    if key.startswith("nvapi-"):
        ok("NVIDIA_API_KEY already set in environment")
        return key

    # Try loading from env file
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            if line.startswith("NVIDIA_API_KEY="):
                key = line.split("=", 1)[1].strip()
                if key.startswith("nvapi-"):
                    ok(f"NVIDIA_API_KEY loaded from {ENV_FILE}")
                    os.environ["NVIDIA_API_KEY"] = key
                    return key

    print("  Get a free key at: https://build.nvidia.com/settings/api-keys")
    print("  (No credit card · No trial period)")
    key = ask("  Paste your NVIDIA_API_KEY (nvapi-...)").strip()
    if not key.startswith("nvapi-"):
        fail("Key must start with 'nvapi-'. Aborting.")
        sys.exit(1)
    os.environ["NVIDIA_API_KEY"] = key
    return key

# ─── Step 2: Install choice ───────────────────────────────────────────────────

def ask_install_choice():
    header("Step 2 — What would you like to install?")
    print()
    print("  1.  Both OpenClaw + Ollama")
    print("  2.  OpenClaw only  (direct NVIDIA API, no bridge needed)")
    print("  3.  Ollama only    (starts the bridge on port 11545)")
    print()
    choice = ask("  Enter 1, 2 or 3", default="1")
    if choice not in ("1", "2", "3"):
        warn("Invalid choice, defaulting to 1 (both)")
        choice = "1"
    labels = {"1": "Both OpenClaw + Ollama", "2": "OpenClaw only", "3": "Ollama only"}
    ok(f"Installing: {labels[choice]}")
    return choice

# ─── Step 3: Generate gemma-4-31b-it.mjs ─────────────────────────────────────

def generate_mjs():
    header("Step 3 — Generating gemma-4-31b-it.mjs")
    if not BRIDGE_SRC.exists():
        fail(f"nvidia-bridge.mjs not found at {BRIDGE_SRC}")
        sys.exit(1)

    src = BRIDGE_SRC.read_text(encoding="utf-8")
    banner = (
        "// Auto-generated by gemma-4-31b-it.py\n"
        f"// Model  : {MODEL_ID}\n"
        "// Run    : node gemma-4-31b-it.mjs\n"
        "//          node gemma-4-31b-it.mjs --chat\n"
        "// API key: loaded from NVIDIA_API_KEY env var\n"
        "//          or ~/.config/nvidia-ollama-bridge/env\n"
        "//\n"
    )
    BRIDGE_OUT.write_text(banner + src, encoding="utf-8")
    BRIDGE_OUT.chmod(0o755)
    ok(f"Created {BRIDGE_OUT.name}")

# ─── Step 4a: Ollama (bridge) ─────────────────────────────────────────────────

def configure_ollama(api_key):
    header("Step 4 — Configuring Ollama bridge")

    # Persist API key to env file
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    existing = ENV_FILE.read_text() if ENV_FILE.exists() else ""
    lines = [l for l in existing.splitlines() if not l.startswith("NVIDIA_API_KEY")]
    lines.append(f"NVIDIA_API_KEY={api_key}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    ok(f"API key saved to {ENV_FILE}")

    # Start the bridge
    info(f"Starting bridge on port {BRIDGE_PORT}…")
    log = Path("/tmp/nvidia-bridge.log")
    proc = subprocess.Popen(
        ["node", str(BRIDGE_OUT)],
        env={**os.environ, "NVIDIA_API_KEY": api_key},
        stdout=log.open("w"),
        stderr=subprocess.STDOUT,
    )
    time.sleep(2)

    if proc.poll() is not None:
        fail(f"Bridge failed to start — check {log}")
        print(log.read_text()[-600:])
        return False

    ok(f"Bridge started (PID {proc.pid}) — logs: {log}")

    # Health check
    r = run(f"wget -qO- http://127.0.0.1:{BRIDGE_PORT}/ 2>/dev/null",
            capture_output=True, text=True, shell=True)
    if '"status"' in r.stdout:
        ok("Bridge health check passed")
    else:
        warn("Bridge may still be starting — check manually:")
        info(f"  wget -qO- http://127.0.0.1:{BRIDGE_PORT}/")

    print()
    ok("Ollama is ready. Chat now:")
    info(f"  OLLAMA_HOST=http://127.0.0.1:{BRIDGE_PORT} ollama run gemma4:latest")
    info(f"  node {BRIDGE_OUT.name} --chat")
    return True

# ─── Step 4b: OpenClaw ────────────────────────────────────────────────────────

def configure_openclaw(api_key):
    header("Step 4 — Configuring OpenClaw")

    if not OPENCLAW_CFG.exists():
        fail(f"openclaw.json not found at {OPENCLAW_CFG}")
        info("Set OPENCLAW_CONFIG env var if your config is elsewhere.")
        return False

    # Backup
    backup = OPENCLAW_CFG.with_suffix(f".json.bak.gemma-{int(time.time())}")
    shutil.copy2(OPENCLAW_CFG, backup)
    ok(f"Backed up openclaw.json → {backup.name}")

    # Patch openclaw.json
    cfg = json.loads(OPENCLAW_CFG.read_text(encoding="utf-8"))
    model_ref = f"nvidia/{MODEL_ID}"

    # Register NVIDIA as a provider
    cfg.setdefault("models", {}).setdefault("providers", {})
    cfg["models"]["providers"]["nvidia"] = {
        "baseUrl": NIM_BASE_URL,
        "api": "openai-completions",
        "models": [
            {"id": MODEL_ID, "contextWindow": 131072, "maxTokens": 16384}
        ]
    }
    ok("models.providers.nvidia configured")

    # Add to models allowlist
    cfg.setdefault("agents", {}).setdefault("defaults", {})
    cfg["agents"]["defaults"].setdefault("models", {})[model_ref] = {}
    ok(f"Registered {model_ref} in agents.defaults.models")

    # Add to defaults fallbacks (never touch primary)
    model_section = cfg["agents"]["defaults"].setdefault("model", {})
    fallbacks = model_section.setdefault("fallbacks", [])
    if model_ref not in fallbacks:
        fallbacks.append(model_ref)
        ok(f"Added {model_ref} to defaults fallbacks")
    else:
        ok(f"{model_ref} already in defaults fallbacks")

    # Add to main agent fallbacks
    for agent in cfg.get("agents", {}).get("list", []):
        if agent.get("id") == "main":
            fb = agent.setdefault("model", {}).setdefault("fallbacks", [])
            if model_ref not in fb:
                fb.append(model_ref)

    OPENCLAW_CFG.write_text(json.dumps(cfg, indent=2, ensure_ascii=False), encoding="utf-8")
    ok("openclaw.json saved")

    # Validate JSON
    try:
        json.loads(OPENCLAW_CFG.read_text())
        ok("openclaw.json is valid JSON")
    except json.JSONDecodeError as e:
        fail(f"JSON validation failed: {e}")
        return False

    # Run openclaw onboard
    if which("openclaw"):
        info("Running openclaw onboard for NVIDIA…")
        r = run(
            "openclaw onboard --auth-choice nvidia-api-key",
            env={**os.environ, "NVIDIA_API_KEY": api_key},
            capture_output=True, text=True
        )
        if r.returncode == 0:
            ok("openclaw onboard completed")
        else:
            warn("openclaw onboard returned an error — config patch still applied")
            if r.stderr:
                info(r.stderr[-300:])
    else:
        warn("openclaw CLI not found in PATH — skipping onboard")
        info("Run manually: openclaw onboard --auth-choice nvidia-api-key")

    # Restart OpenClaw
    _restart_openclaw()

    print()
    ok("OpenClaw is ready.")
    info(f"  Select model in OpenClaw: {model_ref}")
    info("  Default model is unchanged.")
    return True

def _restart_openclaw():
    r = run("systemctl --user restart openclaw 2>/dev/null", capture_output=True)
    if r.returncode == 0:
        ok("OpenClaw restarted via systemd")
        return
    run("pkill -f 'openclaw.*gateway' 2>/dev/null", capture_output=True)
    time.sleep(1)
    claw = shutil.which("openclaw")
    if claw:
        subprocess.Popen(
            [claw, "gateway", "--port", "18789"],
            stdout=open("/tmp/openclaw-restart.log", "w"),
            stderr=subprocess.STDOUT,
        )
        time.sleep(2)
        ok("OpenClaw restarted")
    else:
        warn("Could not restart OpenClaw — please restart it manually")

# ─── --check mode ─────────────────────────────────────────────────────────────

def run_check():
    header("Verifying setup")
    p = w = f = 0

    # API key
    key = os.environ.get("NVIDIA_API_KEY", "")
    if not key and ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            if line.startswith("NVIDIA_API_KEY="):
                key = line.split("=", 1)[1].strip()
    if key.startswith("nvapi-"):
        ok("NVIDIA_API_KEY is set"); p += 1
    else:
        fail("NVIDIA_API_KEY not set"); f += 1

    # Generated .mjs
    if BRIDGE_OUT.exists():
        ok(f"{BRIDGE_OUT.name} exists"); p += 1
    else:
        warn(f"{BRIDGE_OUT.name} not generated yet — run installer"); w += 1

    # Bridge health
    r = run(f"wget -qO- http://127.0.0.1:{BRIDGE_PORT}/ 2>/dev/null",
            capture_output=True, text=True, shell=True)
    if '"status"' in r.stdout:
        ok(f"Bridge running on port {BRIDGE_PORT}"); p += 1
    else:
        warn(f"Bridge not running on port {BRIDGE_PORT}"); w += 1

    # openclaw.json
    if OPENCLAW_CFG.exists():
        cfg = json.loads(OPENCLAW_CFG.read_text())
        if cfg.get("models", {}).get("providers", {}).get("nvidia"):
            ok("openclaw.json: nvidia provider configured"); p += 1
        else:
            warn("openclaw.json: nvidia provider missing"); w += 1
        model_ref = f"nvidia/{MODEL_ID}"
        fb = cfg.get("agents", {}).get("defaults", {}).get("model", {}).get("fallbacks", [])
        if model_ref in fb:
            ok(f"openclaw.json: {model_ref} in fallbacks"); p += 1
        else:
            warn(f"openclaw.json: {model_ref} not in fallbacks"); w += 1
    else:
        warn("openclaw.json not found"); w += 1

    print()
    print(f"  {GREEN}{p} pass{RESET}  {YELLOW}{w} warn{RESET}  {RED}{f} fail{RESET}")
    return f == 0

# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    print(f"\n{BOLD}╔══════════════════════════════════════╗{RESET}")
    print(f"{BOLD}║   nvidia-ollama-bridge  installer    ║{RESET}")
    print(f"{BOLD}╚══════════════════════════════════════╝{RESET}")
    print(f"  Model   : {MODEL_ID}")
    print(f"  Endpoint: {NIM_BASE_URL}")

    if "--check" in sys.argv:
        sys.exit(0 if run_check() else 1)

    if not check_prereqs():
        sys.exit(1)

    api_key = get_api_key()
    choice  = ask_install_choice()

    generate_mjs()

    install_ollama   = choice in ("1", "3")
    install_openclaw = choice in ("1", "2")

    if install_ollama:
        configure_ollama(api_key)

    if install_openclaw:
        configure_openclaw(api_key)

    print()
    print(f"{BOLD}{'═' * 42}{RESET}")
    print(f"{GREEN}{BOLD}  Setup complete!{RESET}")
    print(f"{'═' * 42}")
    if install_ollama:
        print(f"  Ollama  → OLLAMA_HOST=http://127.0.0.1:{BRIDGE_PORT} ollama run gemma4:latest")
        print(f"  Chat    → node {BRIDGE_OUT.name} --chat")
    if install_openclaw:
        print(f"  OpenClaw→ select model  nvidia/{MODEL_ID}")
    print()
    print(f"  Verify  → python3 {Path(__file__).name} --check")
    print()

if __name__ == "__main__":
    main()
